name: Node.js CI

on:
  push:
    branches: [ block* ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version: 18
    - name: branch name  
      run: echo running on branch ${GITHUB_REF##*/}
    - name: Install Dependencies
      run: cd $(echo "${GITHUB_REF##*/}") && npm install
    - name: build
      run: cd $(echo "${GITHUB_REF##*/}") && npm run build --if-present
    - name: run test
      run: cd $(echo "${GITHUB_REF##*/}") && npm test --if-present

