name: Node.js CI

on:
  push:
    branches: [ block* ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version:Use Node.js ${{ matrix.node-version }}
    - name: branch name  
      run: echo running on branch ${GITHUB_REF##*/}
    - name: run ci
      run: cd $(echo "${GITHUB_REF##*/}") && npm ci
    - name: build
      run: cd $(echo "${GITHUB_REF##*/}") && npm run build --if-present
    - name: run test
      run: cd $(echo "${GITHUB_REF##*/}") && npm test

